spring:
  mvc:
    hidden-method:
      filter:
        enabled: true

  thymeleaf:
    enabled: true
    encoding: UTF-8
    cache: false
    check-template: true
    check-template-location: true
    mode: HTML
    template-resolver-order: 0

  datasource:
    url: jdbc:h2:file:./testbd
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate

  h2:
    console:
      enabled: true
      path: /h2-ui
      settings:
        web-allow-others: true
management:
  endpoints:
    web:
      exposure:
        include: "*" #health - need for life